### ISSUE TITLE
Duplicate IDs in generated headings

### ISSUE THREAD

**Issue by nguillaumin** [mattsheppard/markdown-static-site-generator#14]
It seems automatically generated IDs for headings (h1, h2...) can result in duplicates, because the ID generator [naively takes the content of the heading to use an an ID](https://github.com/mattsheppard/markdown-static-site-generator/blob/master/src/main/java/com/kstruct/markdown/utils/MarkdownTocGenerator.java#L52), but multiple headings on the same page may have the same content:

```
# Installation
## Windows
## Linux

# Troubleshooting
## Windows
## Linux
```

This will result in:

```
<h1 id="installation">
<h2 id="windows">
<h2 id="linux">

<h1 id="troubleshooting">
<h2 id="windows">
<h2 id="linux">
```

...with the `windows` and `linux` IDs being duplicated.

This should be fixed to:
* Avoid generating invalid HTML (ID must be unique)
* Avoid breaking anchors / TOC links

**Comment by mattsheppard** [comment]
https://github.com/mattsheppard/markdown-static-site-generator/pull/15 ought to fix it - I'll test it out with some real documents first though.

**Comment by mattsheppard** [comment]
Seemed to work fine on a real data-set, and to solve the described problem within it.

I pushed up 0.0.6 to maven central a few mins ago - In my experience it will take a while (a few hours) to show everywhere, but that ought to fix it.
