### ISSUE TITLE
Need the navigation links to have a class of active. 

### ISSUE THREAD

**Issue by chanified** [mattsheppard/markdown-static-site-generator#4]
The navigation links need to have a class of active set to the top parent item in order for the menu be controllable with CSS.

**Comment by mattsheppard** [comment]
Fixed by providing navigation nodes with node.isPageAt(relativeUri) and node.isParentOfPageAt(relativeUri) mehtods which can be called from within Freemarker to detect the current page (and it's parents) in the navigation.
